### ISSUE TITLE
Framework instead CocoaPods

### ISSUE THREAD

**Issue by devinross** [forcedotcom/DeskMobileSDK-iOS#18]
Hey peoples,

Instead of using cocoapods (do people use that anymore) can there be a .framework that includes everything so plugging this in is 100% easier.

**Comment by nartiles** [comment]
Thanks for the suggestion. We've created an internal work item to address this in a future release.

**Comment by sebbean** [comment]
i'm having a hard time using this code w/ or without cocoapods.

```
Pre-downloading: `DeskKit` from `git@github.com:forcedotcom/DeskMobileSDK-iOS.git`, branch `master`
[!] Unable to find a specification for 'DeskKit'.
```

**Comment by nartiles** [comment]
@sebbean Which version of Cocoapods are you using? We only support the latest stable version which is 0.39.0.
I just tried making a fresh new project with a Podfile pointing to 'DeskKit' and it worked fine. If you're allowed, can you put a copy of your Podfile here?

**Comment by sebbean** [comment]
Must be that I have an old version of CocoaPods. Haven’t used it in a
while. I did pod upgrade but i guess that’s only for the pods themselves
not for the cocoapods gem.
